### 1: Import des librairies

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

### 2: Chargement des données

In [3]:
df = pd.read_csv("data/credit_card_transactions.csv")

df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,merch_zipcode
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.08,-81.18,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.01,-82.05,0,28705.00
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.89,-118.21,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.16,-118.19,0,NaN
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.18,-112.26,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.15,-112.15,0,83236.00
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.23,-112.11,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.03,-112.56,0,NaN
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.42,-79.46,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.67,-78.63,0,22844.00

### 3: Inspection rapide

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 24 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
 23  merch_zipcode          1100702 non-null  float64
dtypes: float64(6), int64(6), object(12)
memory usage: 237.4+ MB

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud,merch_zipcode
count,1296675.00,1296675.00,1296675.00,1296675.00,1296675.00,1296675.00,1296675.00,1296675.00,1296675.00,1296675.00,1296675.00,1100702.00
mean,648337.00,417192042079726656.00,70.35,48800.67,38.54,-90.23,88824.44,1349243636.73,38.54,-90.23,0.01,46825.75
std,374317.97,1308806447000240384.00,160.32,26893.22,5.08,13.76,301956.36,12841278.42,5.11,13.77,0.08,25834.00
min,0.00,60416207185.00,1.00,1257.00,20.03,-165.67,23.00,1325376018.00,19.03,-166.67,0.00,1001.00
25%,324168.50,180042946491150.00,9.65,26237.00,34.62,-96.80,743.00,1338750742.50,34.73,-96.90,0.00,25114.00
50%,648337.00,3521417320836166.00,47.52,48174.00,39.35,-87.48,2456.00,1349249747.00,39.37,-87.44,0.00,45860.00
75%,972505.50,4642255475285942.00,83.14,72042.00,41.94,-80.16,20328.00,1359385375.50,41.96,-80.24,0.00,68319.00
max,1296674.00,4992346398065154048.00,28948.90,99783.00,66.69,-67.95,2906700.00,1371816817.00,67.51,-66.95,1.00,99403.00

In [7]:
df = df.drop(columns=["Unnamed: 0"])

In [8]:
df["trans_date_trans_time"] = pd.to_datetime(df["trans_date_trans_time"])
df["dob"] = pd.to_datetime(df["dob"])

### 4: Vérification des valeurs manquantes

In [5]:
df.isnull().sum()

Unnamed: 0                    0
trans_date_trans_time         0
cc_num                        0
merchant                      0
category                      0
amt                           0
first                         0
last                          0
gender                        0
street                        0
city                          0
state                         0
zip                           0
lat                           0
long                          0
city_pop                      0
job                           0
dob                           0
trans_num                     0
unix_time                     0
merch_lat                     0
merch_long                    0
is_fraud                      0
merch_zipcode            195973
dtype: int64

### 5️: Vérification des doublons

In [6]:
df.duplicated().sum()

0

### 6: Gestion de merch_zipcode

In [9]:
df["merch_zipcode"] = df["merch_zipcode"].fillna(-1)
df["merch_zipcode"] = df["merch_zipcode"].astype(int)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trans_date_trans_time  1296675 non-null  datetime64[ns]
 1   cc_num                 1296675 non-null  int64
 2   merchant               1296675 non-null  object
 3   category               1296675 non-null  object
 4   amt                    1296675 non-null  float64
 5   first                  1296675 non-null  object
 6   last                   1296675 non-null  object
 7   gender                 1296675 non-null  object
 8   street                 1296675 non-null  object
 9   city                   1296675 non-null  object
 10  state                  1296675 non-null  object
 11  zip                    1296675 non-null  int64
 12  lat                    1296675 non-null  float64
 13  long                   1296675 non-null  float64
 14  city_pop               1296675 non-null  int64
 15  job                    1296675 non-null  object
 16  dob                    1296675 non-null  datetime64[ns]
 17  trans_num              1296675 non-null  object
 18  unix_time              1296675 non-null  int64
 19  merch_lat              1296675 non-null  float64
 20  merch_long             1296675 non-null  float64
 21  is_fraud               1296675 non-null  int64
 22  merch_zipcode          1296675 non-null  int32
dtypes: datetime64[ns](2), float64(5), int32(1), int64(5), object(10)
memory usage: 222.6+ MB

### KPIs globaux

In [11]:
total_transactions = len(df)
total_amount = df["amt"].sum()
avg_amount = df["amt"].mean()
fraud_rate = df["is_fraud"].mean() * 100

total_transactions, total_amount, avg_amount, fraud_rate

(1296675, 91222428.9, 70.35103545607033, 0.5788651743883394)

### Analyse par catégorie

In [12]:
category_analysis = (
    df.groupby("category")["amt"]
    .agg(["count", "sum", "mean"])
    .sort_values("sum", ascending=False)
)

category_analysis.head()

                count         sum   mean
category
grocery_pos    123638 14460822.38 116.96
shopping_pos   116672  9307993.61  79.78
shopping_net    97543  8625149.68  88.42
gas_transport  131659  8351732.29  63.43
home           123115  7173928.11  58.27

### Analyse par État (contrôle géographique)

In [13]:
state_analysis = (
    df.groupby("state")["amt"]
    .agg(["count", "sum", "mean"])
    .sort_values("sum", ascending=False)
)

state_analysis.head()

       count        sum  mean
state
TX     94876 6800917.53 71.68
NY     83501 6006499.03 71.93
PA     79847 5771009.53 72.28
CA     56360 4138078.51 73.42
OH     46480 3396146.66 73.07

### Analyse FRAUDE

In [14]:
fraud_analysis = (
    df[df["is_fraud"] == 1]
    .groupby("category")["amt"]
    .agg(["count", "sum", "mean"])
    .sort_values("count", ascending=False)
)

fraud_analysis.head()

               count        sum   mean
category
grocery_pos     1743  543797.90 311.99
shopping_net    1713 1711723.71 999.25
misc_net         915  729266.76 797.01
shopping_pos     843  739245.09 876.92
gas_transport    618    7594.11  12.29

### Détection d’anomalies

##### Z-score

In [15]:
mean_amt = df["amt"].mean()
std_amt = df["amt"].std()

df["z_score"] = (df["amt"] - mean_amt) / std_amt

anomalies = df[df["z_score"].abs() > 3]
len(anomalies)

12738

#### Top Anomalies

In [16]:
anomalies.sort_values("amt", ascending=False).head(10)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,merch_zipcode,z_score
787549,2019-12-01 16:19:23,4979422371139333,fraud_Satterfield-Lowe,travel,28948.90,Kelly,Zimmerman,F,1893 Katie Tunnel,Westerville,NE,68881,41.42,-99.38,73,Product designer,1935-02-10,309c4bf7fc47b1ddee5ad883bcf634b6,1354378763,42.32,-99.14,0,68711,180.14
793677,2019-12-02 15:53:46,675909898057,"fraud_Monahan, Hermann and Johns",travel,27390.12,Christopher,Henry,M,1198 Robert Stravenue Apt. 479,Armonk,NY,10504,41.14,-73.70,7987,Television/film/video producer,1964-03-16,2ca9bd5df126cc35e541a4f2c2551197,1354463626,41.67,-74.66,0,12751,170.41
1234797,2020-05-30 17:31:30,60423098130,"fraud_Monahan, Hermann and Johns",travel,27119.77,Jason,Gray,M,875 Amy Point,Amorita,OK,73719,36.94,-98.25,83,Barrister's clerk,1958-07-28,916093eeab1831be71d49362bf5b7be5,1369935090,37.29,-97.25,0,67119,168.73
606211,2019-09-14 22:19:01,30408301059761,fraud_Boyer-Haley,travel,26544.12,Brandon,Pittman,M,2881 Frey Village,Cross,SC,29436,33.34,-80.19,4471,Occupational hygienist,1973-10-09,dda9d800d37a9fc2c086a836d66b0588,1347661141,33.02,-80.13,0,29456,165.13
352894,2019-06-14 20:15:38,5540636818935089,fraud_Hackett Group,travel,25086.94,Kenneth,Foster,M,329 Michael Extension,Lawrence,MA,1843,42.69,-71.16,76383,Geoscientist,1985-04-04,0b902a1e549c98b949444a7557da2403,1339704938,42.40,-71.47,0,1754,156.05
187885,2019-04-07 15:32:23,6538441737335434,fraud_Tillman LLC,travel,17897.24,Gina,Grimes,F,444 Robert Mews,Clarks Mills,PA,16114,41.39,-80.18,606,Energy manager,1997-09-22,1c9f2b574fb9bf860c76ea200252fe05,1333812743,41.36,-79.67,0,16346,111.20
1100138,2020-04-02 14:23:21,36153880429415,"fraud_Reichel, Bradtke and Blanda",travel,15305.95,Erik,Stevens,M,84033 Pitts Overpass,Lakeland,FL,33809,28.18,-81.96,237282,Plant breeder/geneticist,1949-10-13,17242c80d9a67bac27901c0676ab56aa,1364912601,28.57,-81.07,0,32820,95.03
752016,2019-11-17 20:00:17,2264937662466770,fraud_Goyette-Herzog,travel,15047.03,Juan,Sherman,M,5939 Garcia Forges Suite 297,San Antonio,TX,78214,29.36,-98.49,1595797,Land,1995-10-17,969e374d8c4e1a628b60150391a70742,1353182417,29.85,-98.22,0,78133,93.42
150564,2019-03-22 13:17:34,4450831335606294,"fraud_Larson, Quitzon and Spencer",travel,15034.18,Donna,Davis,F,6760 Donovan Lakes,Clayton,OK,74536,34.59,-95.38,1760,Occupational psychologist,1972-01-20,938cfcbde2c3a64c38b7855eb8288de0,1332422254,35.27,-95.03,0,74462,93.34
1245847,2020-06-02 18:45:24,3592931352252641,fraud_Lynch-Mohr,travel,14849.74,Dylan,Garcia,M,923 Jordan Road,Afton,MN,55001,44.87,-92.82,2916,Barrister's clerk,1935-06-29,a3eee563b00b16af433ceb069178da74,1370198724,44.84,-92.50,0,54022,92.19

#### Anomalies par catégorie

In [17]:
anomaly_by_category = (
    anomalies.groupby("category")["amt"]
    .count()
    .sort_values(ascending=False)
)

anomaly_by_category.head()

category
shopping_net    4085
shopping_pos    3934
misc_net        2074
travel          1308
misc_pos        1224
Name: amt, dtype: int64

### Préparation pour Power BI

In [18]:
monthly_summary = (
    df.set_index("trans_date_trans_time")
      .resample("M")
      .agg(
          total_amount=("amt", "sum"),
          avg_amount=("amt", "mean"),
          fraud_count=("is_fraud", "sum"),
          transaction_count=("amt", "count")
      )
      .reset_index()
)

C:\Users\hp\AppData\Local\Temp\ipykernel_20784\3894141927.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample("M")

In [19]:
df.to_csv("data/clean_transactions.csv", index=False)
monthly_summary.to_csv("data/monthly_summary.csv", index=False)
anomalies.to_csv("data/anomalies.csv", index=False)